### ISSUE TITLE
Create Github Action to make releases

### ISSUE THREAD

**Issue by bradmccoydev** [sustainable-computing-io/kepler-action#34]
This repo should have releases associated with it so when a change is done to the main branch it will trigger a release as it is a dependency for other workflows such as the kepler-helm-chart repo.

example:
Now in the keptler-helm-chart it calls this action using

```bash
- name: use kepler action for kind cluster build
    uses: sustainable-computing-io/kepler-action@main
    with:
      runningBranch: kind
```

Because this is hardcoded to the main branch if there is an error it will break other workflows, therefore pinning it to a release is a better practice, folks can also point to the commit sha of that release for better security.

using versioning it would look like this instead:
```bash
- name: use kepler action for kind cluster build
    uses: sustainable-computing-io/kepler-action@v0.0.1
    with:
      runningBranch: kind
```

I am happy to do this PR if approved, and it wont break anything existing as that still points to main until we use the version.

**Comment by SamYuan1990** [comment]
I like to have tag, but I don't like the evidence.
Once up on a time, we have an network issue(seems related with GHA changes/updates.) and we benefits from every repo use main branch directly.

> main branch if there is an error it will break other workflows

as this repo has it own CI, so in major case, it won't break or can reproduce by it's own CI.

> folks can also point to the commit sha of that release for better security.

I didn't get this point...

if we are going to have a tag, in my point of view, which means we should make changes:
- for each software dependency has a tag/version as input parameter.
- for each parameter has a default value.
```
- name: use kepler action for kind cluster build
    uses: sustainable-computing-io/kepler-action@v0.0.1
    with:
      runningBranch: kind
      kind_version: ${env.kind_version}
      kubectl_version: ${env.kubectl_version}
```
hence each repo can just update kind version without a release in this repo.

so far are we going to have any change for this repo? @rootfs 
if not, it seems one single version is good enough for now.
or I hope @bradmccoydev provides more values for us to make this repo with tag for today.
