### ISSUE TITLE
Features and Design for v1

### ISSUE THREAD

**Issue by SamYuan1990** [sustainable-computing-io/kepler-action#4]
- A parameter to control workflows.

- [x] Workflow install BCC.
```
      - name: use kepler action for install bcc
        uses: sustainable-computing-io/KeplerK8SAction@main
        with:
          runningBranch: bcc
```
- [x] Workflow prepare kind cluster with prometheus operator.
```
      - name: use kepler action for set up kind cluster
        uses: sustainable-computing-io/KeplerK8SAction@main
        with:
          runningBranch: kind
```
- [x] Workflow prepare micro shift(OpenShift) cluster with prometheus operator.
